# Questions: result different 
between `np.linalg.lstsq` and `linear_model.LinearRegression`

In [25]:
from sklearn import linear_model
import numpy as np
A = np.array([[1, 0], [0, 1]])
b = np.array([1, 0])
x , _, _, _ = np.linalg.lstsq(A,b)
x

array([ 1.,  0.])

In [26]:
clf = linear_model.LinearRegression()
clf.fit(A, b)                              
coef = clf.coef_
coef

array([ 0.5, -0.5])

# Set fit_intercept and get the same result

In [27]:
clf = linear_model.LinearRegression(fit_intercept=False)
clf.fit(A, b)                              
coef = clf.coef_
coef

array([ 1.,  0.])

# Why?

**linear_model.LinearRegression will do data pre-process**
[here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/linear_model/base.py#L144)

# Normalize data to get the same result

In [28]:
# Normalization
from sklearn.preprocessing import StandardScaler
A = np.array([[1, 0], [0, 1]])
X_scaler = StandardScaler()
A = X_scaler.fit_transform(A)

F:\Users\bin_yin\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\validation.py:420: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
F:\Users\bin_yin\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\validation.py:420: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [29]:
from sklearn import linear_model
import numpy as np

b = np.array([1, 0])
x , _, _, _ = np.linalg.lstsq(A,b)
x

array([ 0.25, -0.25])

In [30]:
clf = linear_model.LinearRegression()
clf.fit(A, b)                              
coef = clf.coef_
coef


array([ 0.25, -0.25])