In [2]:
from mxnet import nd

# 1. create 1D array

In [4]:
# 1-d array

x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [5]:
x.shape

(12,)

In [6]:
x.size

12

# 2. reshape

In [7]:
x = nd.arange(12)
x = x.reshape((3,4))
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

# 3. zeros/ones

In [8]:
x = nd.zeros((3,4,5))
x.shape

(3, 4, 5)

In [9]:
x = nd.ones((3,4))
x


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

# 4. list to array

In [10]:
l = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
]
x = nd.array(l)
x


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

# 5. index

In [11]:
x


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

In [12]:
x[0][0]


[1.]
<NDArray 1 @cpu(0)>

In [13]:
x[0,1]


[2.]
<NDArray 1 @cpu(0)>

In [16]:
x[:2,:2]


[[1. 2.]
 [4. 5.]]
<NDArray 2x2 @cpu(0)>