# 1. normal dbscan

In [11]:
%%timeit
from sklearn.cluster import DBSCAN
import numpy as np
X = np.array([[1, 2], [2, 2], [2, 3],[8, 7], [8, 8], [25, 80]])
clustering = DBSCAN(eps=3, min_samples=2).fit(X)
clustering.labels_

298 µs ± 4.41 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
print(clustering.labels_)

[ 0  0  0  1  1 -1]


# 2. dbscan with precomputed metric

In [12]:
from sklearn.metrics.pairwise import euclidean_distances
X = np.array([[1, 2], [2, 2], [2, 3],[8, 7], [8, 8], [25, 80]])
M  = euclidean_distances(X)

In [13]:
M

array([[ 0.        ,  1.        ,  1.41421356,  8.60232527,  9.21954446,
        81.60882305],
       [ 1.        ,  0.        ,  1.        ,  7.81024968,  8.48528137,
        81.32035416],
       [ 1.41421356,  1.        ,  0.        ,  7.21110255,  7.81024968,
        80.36168241],
       [ 8.60232527,  7.81024968,  7.21110255,  0.        ,  1.        ,
        74.95331881],
       [ 9.21954446,  8.48528137,  7.81024968,  1.        ,  0.        ,
        73.97972695],
       [81.60882305, 81.32035416, 80.36168241, 74.95331881, 73.97972695,
         0.        ]])

In [15]:
%%timeit
from sklearn.cluster import DBSCAN
import numpy as np
X = np.array([[1, 2], [2, 2], [2, 3],[8, 7], [8, 8], [25, 80]])
clustering = DBSCAN(eps=3, min_samples=2, metric="precomputed").fit(M)
clustering.labels_

267 µs ± 7.25 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
print(clustering.labels_)

[ 0  0  0  1  1 -1]


In [ ]:
# same result.