# 1. init

In [1]:
! pip install chainer-chemistry

    100% |████████████████████████████████| 61kB 696kB/s ta 0:00:01
    100% |████████████████████████████████| 522kB 1.8MB/s ta 0:00:01
    100% |████████████████████████████████| 51kB 3.4MB/s ta 0:00:01
  Running setup.py bdist_wheel for chainer-chemistry ... done
  Stored in directory: /root/.cache/pip/wheels/cd/ad/92/2437e7e756082248054bc5d1fa42f1ddd8d13546d98246c018
  Running setup.py bdist_wheel for chainer ... done
  Stored in directory: /root/.cache/pip/wheels/91/82/5d/4ef2ad99aa90614010eced537d2074b31c5c15f75cb278d272
Successfully built chainer-chemistry chainer
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
mkl-random 1.0.1 requires cython, which is not installed.
mxnet 1.2.1 requires graphviz<0.9.0,>=0.8.1, which is not installed.
mkl-fft 1.0.4 requires cython, which is not installed.
tensorflow 1.10.0 has requirement numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.15.0 which is incompatible.
tensorflow 1.10.0 has requirement setuptools<=39.1.0, but you'l

In [5]:
! conda install -c rdkit rdkit

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.5.12

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /root/anaconda3/envs/envtf

  added / updated specs: 
    - rdkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    py-boost-1.65.1            |   py35hf484d3e_4         297 KB
    olefile-0.46               |           py35_0          48 KB
    pillow-5.2.0               |   py35heded4f4_0         589 KB
    rdkit-2018.03.4.0          |   py35h71b666b_1        19.7 MB  rdkit
    libboost-1.65.1            |       habcd387_4        19.2 MB
    ------------------------------------------------------------
                                           Total:        39.8 MB

The following NEW packages will be INSTALLED:

    libboost: 1.65.1-habcd387_4      

# 2. check data (tox21)

In [2]:
from chainer_chemistry import datasets as D

In [3]:
dir(D) # list all contains dataset

['NumpyTupleDataset',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'get_qm9',
 'get_qm9_filepath',
 'get_qm9_label_names',
 'get_tox21',
 'get_tox21_filepath',
 'get_tox21_label_names',
 'molnet',
 'numpy_tuple_dataset',
 'qm9',
 'tox21']

In [25]:
train, val, test = D.get_tox21() # download dataset

100%|██████████| 647/647 [00:01<00:00, 520.26it/s]


In [26]:
x_train, y_train = train.get_datasets()

In [27]:
y_train

array([[-1, -1, -1, ...,  0, -1, -1],
       [-1, -1, -1, ...,  0, -1, -1],
       [-1, -1, -1, ...,  0, -1, -1],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  1, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  1]], dtype=int32)

In [28]:
x_train

array([array([ 6,  7,  6,  6,  6,  7,  6,  6,  6,  6,  6,  6,  6,  6,  7,  6,  6,
        7,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  6,  6,  7,  6,  6, 17],
      dtype=int32),
       array([ 8,  6,  8,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6, 35,  6,  8,  6,
       35,  6,  8,  6,  6, 35,  6,  8,  6, 35,  6,  6, 11, 11],
      dtype=int32),
       array([6, 8, 6, 6, 6, 8, 6, 6, 6, 6, 8, 6, 6, 8, 6, 6, 6, 6, 6, 8, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 6, 6, 6, 6, 6, 6, 8, 6, 8, 6,
       6, 8, 8, 6, 6, 6, 8, 6, 6, 8, 6, 8, 8, 8, 8, 6, 6, 6, 8, 6, 7],
      dtype=int32),
       ..., array([16,  6,  7,  6,  6,  7], dtype=int32),
       array([ 6,  6,  8, 15, 16,  8,  6,  6,  8,  6,  6,  6,  6,  7,  8,  8,  6,
        6], dtype=int32),
       array([ 6,  6,  6,  6,  8,  6,  8,  6,  6, 16,  6,  8,  6,  8,  6,  6, 16,
        6,  8,  6,  8,  6,  6, 16], dtype=int32)], dtype=object)